main:
  push:
    - name: sync
      runner:
        cpus: 2
      imports: https://cnb.cool/ecustcic/key/-/blob/main/env.yml
      stages:
        - name: sync to github
          image: tencentcom/git-sync
          settings:
            target_url: https://github.com/ECUSTCIC-CodeHub/FullStack-Voyage.git
            auth_type: https
            username: ${GITHUB_USERNAME}
            password: ${GITHUB_ACCESS_TOKEN}
            force: true
    - name: edgeone
      runner:
        cpus: 2
      imports: https://cnb.cool/ecustcic/key/-/blob/main/env.yml
      stages:
        # 构建当前项目
        - name: Build Current Project
          image: node:22
          script: "node -v && sed -i \"s|base: '/FullStack-Voyage/',|base: '/',|\" docs/.vuepress/config.ts && corepack enable && pnpm install --frozen-lockfile && pnpm run docs:build"
        # 将构建输出部署到 EdgeOne Pages
        - name: Deploy to EdgeOne Pages
          image: node:22
          script: npx edgeone pages deploy ./docs/.vuepress/dist -n fullstackvoyage -t $EDGEONE_API_TOKEN
  
  # Web触发器配置
  web_trigger:
    - name: manual-edgeone-push
      runner:
        cpus: 2
      imports: https://cnb.cool/ecustcic/key/-/blob/main/env.yml
      stages:
        # 构建当前项目
        - name: Build Current Project
          image: node:22
          script: "node -v && sed -i \"s|base: '/FullStack-Voyage/',|base: '/',|\" docs/.vuepress/config.ts && corepack enable && pnpm install --frozen-lockfile && pnpm run docs:build"
        # 将构建输出部署到 EdgeOne Pages
        - name: Deploy to EdgeOne Pages
          image: node:22
          script: npx edgeone pages deploy ./docs/.vuepress/dist -n fullstackvoyage -t $EDGEONE_API_TOKEN